name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/README.md'
      - '**/docker.yaml'
  pull_request:
    branches: [ "master" ]

jobs:
  job-with-mysql-8_0:
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTOR: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    services:
      db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: demo
          MYSQL_USER: demo
          MYSQL_PASSWORD: demo
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - name: 'Set up latest Oracle JDK 19'
      uses: oracle-actions/setup-java@v1
      with:
        website: oracle.com
        release: 19
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build